<?php
namespace App\Http\Requests\Procurement;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
class ProcurementActionRequest extends FormRequest { public function authorize(): bool { return true; } public function rules(): array { return ['action'=>['required',Rule::in(['submit','manager_approve','asset_team_approve','budget_tl_approve','assign_budget_code','expert_complete','final_manager_approve','records_process','finance_complete','save_manager_final_attachment_draft','save_record_attachment_draft','reject'])],'note'=>['nullable','string'],'reason'=>['required_if:action,reject','nullable','string'],'budget_code'=>['required_if:action,assign_budget_code','nullable','string','max:100'],'reference_no'=>['nullable','string','max:100'],'official_date'=>['nullable','date'],'official_date_ec'=>['nullable','string','max:30'],'receiver_type'=>['nullable','string','max:80'],
            'send_to_user_id'=>['nullable','integer','exists:users,id'],
            'receiver_id'=>['nullable','integer','exists:users,id'],
            'department_id'=>['required_if:action,manager_approve','nullable','integer','exists:departments,id'],
            'team_leader_user_id'=>['required_if:action,manager_approve','nullable','integer','exists:users,id'],
            'assigned_team_leader_id'=>['nullable','integer','exists:users,id'],
            'budget_department_id'=>['required_if:action,asset_team_approve','nullable','integer','exists:departments,id'],
            'budget_team_leader_user_id'=>['required_if:action,asset_team_approve','nullable','integer','exists:users,id'],
            'budget_team_leader_id'=>['nullable','integer','exists:users,id'],
            'forward_to_role'=>['nullable',Rule::in(['asset_team_leader','machinery_team_leader','asset','machinery','fixed_asset','machinary'])],
            'approval_description'=>['nullable','string','max:2000'],
            'attachment_to'=>['nullable','string','max:255'],
            'attachment_address'=>['nullable','string','max:255'],
            'attachment_case'=>['nullable','string','max:255'],
            'attachment_body'=>['nullable','string'],
            'attachment_gg'=>['nullable','array'],
            'attachment_gg.*'=>['nullable','string','max:255'],
            'attachment_reference_no'=>['nullable','string','max:100'],
            'attachment_official_date_ec'=>['nullable','string','max:30'],
            'items'=>['nullable','array'],
            'items.*.item_name'=>['required_with:items','string','max:255'],
            'items.*.specification'=>['nullable','string','max:255'],
            'items.*.unit'=>['nullable','string','max:50'],
            'items.*.quantity'=>['required_with:items','numeric','min:0'],
            'items.*.estimated_unit_cost'=>['nullable','numeric','min:0'],
            'items.*.estimated_total_cost'=>['nullable','numeric','min:0'],
        ]; } }
